[toolchain]
profile = "minimal"
# use the nightly version of a stable toolchain, see <https://forge.rust-lang.org/>
channel = "nightly-2023-07-12"
components = ["rust-src", "llvm-tools-preview", "rustfmt", "clippy"]
